config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'games#index'

  resources :games do
    post 'throw', on: :member
    resources :frames, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frame.rb
class GameOverError < StandardError; end
class Frame < ApplicationRecord
  MAX_FRAME_NUMBER = 10
  MIN_FRAME_NUMBER = 1
  STRIKE_BALLS = 10
  DEEP_SCORE_INIT_COUNT = 2
  DEEP_SCORE_AFTER_DOUBLE_STRIKE_COUNT = 1
  DEEP_SCORE_AFTER_SPARE_COUNT = -1

  belongs_to  :game

  validates_presence_of :game, :number, :player_number
  validates :number, numericality: { greater_than_or_equal_to: MIN_FRAME_NUMBER, less_than_or_equal_to: MAX_FRAME_NUMBER }
  validate :validate_score

  def throws
    [self.throw1, self.throw2, self.throw3]
  end

  def throw!(pins_down)
    raise GameOverError if game_over?
    add_throw(pins_down)
    save!
  end

  def next_player_number
    next_number = player_number + (finished? ? 1 : 0)
    return 1 if next_number > game.players_count
    next_number
  end

  def next_frame_number
    return number if final?
    number + (finished? ? 1 : 0)
  end

  def game_over?
    final? && finished?
  end

  def throw_number
    throws.reject(&:nil?).count + 1
  end

  def finished?
    if final?
      return true if (strike? || spare?) && self.throws.third
      return true if (!strike? && !spare?) && self.throws.second
      return false
    else
      return strike? || self.throws.second
    end
  end

  def final?
    self.number == MAX_FRAME_NUMBER
  end


  def score(deep_count=DEEP_SCORE_INIT_COUNT)
    return throws_score(1) if deep_count == DEEP_SCORE_AFTER_SPARE_COUNT || deep_count < DEEP_SCORE_AFTER_DOUBLE_STRIKE_COUNT

    if strike?
      return throws_score(1,2) if final? && deep_count < DEEP_SCORE_INIT_COUNT
      return throws_score(1,2,3) if final?
      return throws_score(1) + next_frame_by_player_score(deep_count-1)
    end

    return throws_score(1,2) if deep_count < DEEP_SCORE_INIT_COUNT
    return throws_score(1,2,3) if final?
    return throws_score(1,2) + next_frame_by_player_score(DEEP_SCORE_AFTER_SPARE_COUNT) if spare?

    throws_score(1,2)
  end

  def player_name
    game.players_names[self.player_number-1] if game.players_names
  end

  private

  def throws_score(*throws)
    throws.collect { |i| self.throws[i-1].to_i }.sum
  end

  def next_frame_by_player_score(deep_count)
    _next_frame = next_frame_by_player
    _next_frame ? _next_frame.score(deep_count) : 0
  end

  def next_frame_by_player
    game.frames.where(player_number: self.player_number, number: self.number + 1).first
  end

  def strike?
    self.throws.first == STRIKE_BALLS
  end

  def spare?
    !strike? && throws_score(1,2) == STRIKE_BALLS
  end

  def add_throw(val)
    if self.throw1.nil?
      self.throw1 = val 
    elsif self.throw2.nil?
      self.throw2 = val
    elsif self.throw3.nil?
      self.throw3 = val
    end
  end

  def valid_score?
    if final?
      return false if strike? && throws_score(1,2,3) > 30
      return false if spare? && throws_score(1,2,3) > 20
      return false if !strike? && !spare? && throws_score(1,2,3) > STRIKE_BALLS
    else
      return false if throws_score(1,2,3) > STRIKE_BALLS
    end
    return true
  end

  def validate_score
    errors.add(:base, "Invalid thrown pins") unless valid_score?
  end


end

app/models/game.rb
class Game < ApplicationRecord
  MIN_PLAYERS = 1
  MAX_PLAYERS = 8

  has_many :frames, dependent: :destroy

  serialize :players_names

  validates_presence_of :players_count
  validates :players_count, numericality: { greater_than_or_equal_to: MIN_PLAYERS, less_than_or_equal_to: MAX_PLAYERS }

  def throw!(pins_down)
    frame = last_frame(current_player_number)
    frame = frames.create!(player_number: current_player_number, number: current_frame_number) if switch_frame?(frame)
    frame.throw!(pins_down)
    frame
  end

  def score(player_number = 1)
    frames.where(player_number: player_number).map(&:score).sum
  end

  def game_over?(player_number = nil)
    if player_number
      last_frame(player_number).try(:game_over?)
    else
      (1..self.players_count).all? { |player_number| game_over?(player_number) }
    end
  end


  def current_frame_number
    return 1 unless last_frame(current_player_number)
    last_frame(current_player_number).next_frame_number
  end

  def current_player_number
    return 1 unless last_frame
    last_frame.next_player_number
  end

  def current_player_name
    self.players_names[current_player_number-1] if self.players_names
  end

  def current_frame_throw
    return 1 if last_frame.nil? || last_frame.finished?
    last_frame.throw_number
  end

  private

  def last_frame(player_number = nil)
    where_opts = player_number ? { player_number: player_number } : {}
    frames.where(where_opts).last
  end

  def switch_frame?(frame)
    frame.nil? || (frame.finished? && !frame.final?)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
  def index
    @game = Game.find(params[:game_id])
    @frames = @game.frames.order("player_number, number")
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :throw, :destroy]

  def create
    @game = Game.new(game_params[:game])
    if @game.save
      redirect_to @game, notice: 'Game added, roll'
    else
      render :new
    end
  end

  def show
  end

  def index
    @games = Game.order(:created_at).last(15)
  end

  def throw
    notice = "Ball has been thrown"
    begin
      @game.throw!(params[:pins_down])
    rescue ActiveRecord::RecordInvalid => e
      notice = e.message
    end

    if @game.game_over?
      redirect_to games_path, notice: 'Game over'
    else
      redirect_to @game, notice: notice
    end
  end

  def new
    @game = Game.new
  end

  def destroy
    @game.destroy
    redirect_to games_path, notice: "Game has been destroyed"
  end

  private

  def find_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.permit(game: [:players_count, {:players_names => []}])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/frames/_frame_stat.html.haml
%h2= "Frames for Game: #{game.id}"
-if frames.present?
  .row
    .col-sm-1 Number
    .col-sm-3 Player
    .col-sm-1 Throw1
    .col-sm-1 Throw2
    .col-sm-1 Throw3
    .col-sm-1 Score
  - frames.each do |frame|
    .row
      .col-sm-1= frame.number
      .col-sm-3= "#{frame.player_number} (#{frame.player_name})"
      .col-sm-1= frame.throw1
      .col-sm-1= frame.throw2
      .col-sm-1= frame.throw3
      .col-sm-1= frame.score

app/views/frames/index.html.haml
= render partial: "frame_stat", locals: { game: @game, frames: @frames }
= link_to "Games list", games_path

app/views/games/index.html.haml
%h2 Last Played Games
-if @games.present?
  .row
    .col-sm-1 GameID
    .col-sm-2 Count of players
    .col-sm-2 Score
    .col-sm-1 Frames
    .col-sm-1 Finished?
    .col-sm-2 Created at
    .col-sm-2 Actions
  - @games.each do |game|
    .row
      .col-sm-1= game.id
      .col-sm-2= game.players_count
      .col-sm-2= game.decorate.players_score
      .col-sm-1= link_to "#{game.frames.count}", game_frames_path(game)
      .col-sm-1= game.game_over?.to_s
      .col-sm-2= game.created_at.to_s(:db)
      .col-sm-3
        = link_to "Del", game_path(game), method: :delete, data: { confirm: "Are you sure?" }
        -unless game.game_over?
          = link_to "Continue", game_path(game)
= link_to "Play new game", new_game_path

app/views/games/new.html.haml
.row
  .col-sm-4
    %h2 Define players names
    -if @game.errors.present?
      .alert.alert-danger
        %ul
          - @game.errors.full_messages.each do |message|
            %li= message
    .well
      = simple_form_for @game do |f|
        = f.input :players_count, as: :select, collection: (Game::MIN_PLAYERS..Game::MAX_PLAYERS).to_a, default: 1
        - Game::MAX_PLAYERS.times do |number|
          - visibility_class = number.zero? ? "player_visible" : "player_hidden"
          - wrapper_class = visibility_class + " player_wrapper_#{number+1}" 
          = f.input :players_names, as: :string, multiple: true, label: "Player #{number+1}", input_html: { name: 'game[players_names][]', id: "player#{number+1}"}, wrapper_html: { class: wrapper_class }
        = f.submit "Start game"
    = link_to "Back to games", games_path
#settings.player_hiddden{data: { max_players: Game::MAX_PLAYERS }}

app/views/games/show.html.haml
.row
  .col-sm-4
    .well
      %h2= "Game ##{@game.id}"
      .setup
        = "Setup: players_count: #{@game.players_count}"
      .status
        = "Frame: #{@game.current_frame_number}, Player id: #{@game.current_player_number}, Player name: #{@game.current_player_name}, Throw: #{@game.current_frame_throw}"
      .score
        = "Players score: #{@game.decorate.players_score}"

    .well
      = simple_form_for @game, url: throw_game_path(@game), method: :post do |f|
        .throw_ball
          .label
            Pins down
          = text_field_tag :pins_down
        = f.submit "Throw!"
    = link_to "Back to games", games_path
  .col-sm-8
    =render partial: "frames/frame_stat", locals: { game: @game, frames: @game.frames }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bowling</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="notice"><%= flash[:notice] %></div>
    <div class="error"><%= flash[:error] %></div>
    <%= yield %>
  </body>
</html>